USE [master]
GO
/****** Object:  Database [GoProject]    Script Date: 01/02/2017 12:35:34 ب.ظ ******/
DROP DATABASE IF EXISTS [GoProject]
GO
/****** Object:  Database [GoProject]    Script Date: 01/02/2017 12:35:34 ب.ظ ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'GoProject')
BEGIN
CREATE DATABASE [GoProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GoProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GoProject.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GoProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\GoProject_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO
ALTER DATABASE [GoProject] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GoProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GoProject] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GoProject] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GoProject] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GoProject] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GoProject] SET ARITHABORT OFF 
GO
ALTER DATABASE [GoProject] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GoProject] SET AUTO_SHRINK ON 
GO
ALTER DATABASE [GoProject] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GoProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GoProject] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GoProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GoProject] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GoProject] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GoProject] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GoProject] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GoProject] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO
ALTER DATABASE [GoProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GoProject] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GoProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GoProject] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GoProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GoProject] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GoProject] SET RECOVERY FULL 
GO
ALTER DATABASE [GoProject] SET  MULTI_USER 
GO
ALTER DATABASE [GoProject] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GoProject] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GoProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GoProject] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [GoProject] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'GoProject', N'ON'
GO
ALTER DATABASE [GoProject] SET QUERY_STORE = OFF
GO
USE [GoProject]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE [GoProject] SET  READ_WRITE 
GO
